# LE DECIMOS LOS INSTALADORES QUE NECESITAMOS TENER EN EL CONTENEDOR

FROM node:18-bullseye 

# CARPETA DONDE SE REQUIERE QUE TRABAJE
WORKDIR /app

#INDICAR EL PUERTO

EXPOSE 8080

#LOS PUNTOS INDICAN QUE COPIAMOS TODO


COPY . .
#DEJAMOS QUE TODAS LAS LIBRERIAS DEL PROYECTO SE DESCARGUEN 

RUN npm install

#COMANDO PARA LA EJECUCIÓN DEL PROYECTO

CMD { "npm","start" }
